### ISSUE TITLE
can't reproduce your project，need help

### ISSUE THREAD

**Issue by ftiannew** [romanspb80/evpn-for-ovn#1]
Roman，
         I can‘t reproduce your project, something wrong with Ryu.actually I can't reproduce the rest_vtep application in my lab due to the python version compatibility, I think.
       what interested me is how you make the OVN forwarding the packets to the vtep, I couldn't find any document by searching.
would you please help ?
    thanks
Tian.

**Comment by romanspb80** [comment]
Hello Tian

Regarding your question about the vtep for OVN.
To organize the vtep, two associated entities are created: vxlan-port with name "vxlan_192.168.10.10_10" in OVS and vxlan-port with same name in OVN. And they are associated through the field "external_ids" in OVSDB:

*vagrant@microstack:~$ sudo ovs-vsctl get interface vxlan_192.168.10.10_10 external_ids*
*{iface-id=vxlan_192.168.10.10_10}*

Some dependencies have become incompatible over time. 
So I redesigned the project. Try again, please. Everything is being reproduced now.
